services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: repo_scrapper_backend
    ports:
      - "8001:8000"  # Local machine ka port 8001 -> Container ka port 8000
    env_file:
      - path: ./server/.env
        required: false
      - path: .env
        required: false
    restart: unless-stopped