apiVersion: v1
kind: Secret
metadata:
  name: repo-scrapper-secrets
  namespace: repo-scrapper
type: Opaque
stringData:
  GROK_API_KEY_1: "GROK_API_KEY_1"
  GROK_API_KEY_2: "GROK_API_KEY_2"
  GITHUB_TOKEN: "ghp_your_github_token_here" 