apiVersion: v1
kind: Service
metadata:
  name: repo-scrapper-service
  namespace: repo-scrapper
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: repo-scrapper-backend